Add Contact form to the app
JohnFTitor/portfolioFirstProject pull request #3
Opened 2021-11-30 23:33 UTC by JohnFTitor

- Created a contact form set to my Formspree account
- Styled elements to meet UX design, following the template provided
- Added a footer with social media links 

We work together with the pair programming technique 

![](https://media3.giphy.com/media/3NnnS6Q8hVPZC/giphy.gif)

2021-11-30 23:45 UTC, VanessaAoki requested changes
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @JohnFTitor  and @vanillainanutshell , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Your README file looks very professional and the PR has a descriptive title/summary of the implemented changes :memo: 
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 
- [x] Used flexbox to style the form elements 🎨  

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

#### You should also consider:
- [ ] To keep your repo professional, you should consider editing the README author's section, adding your social media!

![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 23:45 UTC, VanessaAoki commented on index.html
> +                <textarea name="comment" maxlength="500">Enter text here</textarea>
- [ ] Great job setting up formspree correctly 👏  you should consider adding "required" to the `<textarea>`, I was able to submit the form with a blank field.

2021-11-30 23:45 UTC, VanessaAoki commented on index.html
> +    <title> My portfolio </title>
- [ ] [OPTIONAL]: To keep your project even more professional, you should consider adding a more descriptive title, what about having "your name's portfolio", for instance?

2021-12-01 16:39 UTC, rotimiazeez approved these changes
# Hi Team😉, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 👏
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 16:42 UTC, merged